'use strict';

// Load .env only when not running on AWS Lambda
if (!process.env.AWS_EXECUTION_ENV) {
  require('dotenv').config();
}

const {
  TOPIC_ARN, QUEUE_URL,

  EXCHANGE_1,   PAGE_URL_1,   API_URL_1,   API_URL_BUILDER_1,
  EXCHANGE_2,   PAGE_URL_2,   API_URL_2,   API_URL_BUILDER_2,
  EXCHANGE_3,   PAGE_URL_3,   API_URL_3,   API_URL_BUILDER_3,

  EXCHANGE_100, PAGE_URL_100, API_URL_100, API_URL_BUILDER_100,
  EXCHANGE_101, PAGE_URL_101, API_URL_101, API_URL_BUILDER_101,
} = process.env;

module.exports = {
  TOPIC_ARN, QUEUE_URL,

  EXCHANGE_1,   PAGE_URL_1,   API_URL_1,   API_URL_BUILDER_1,
  EXCHANGE_2,   PAGE_URL_2,   API_URL_2,   API_URL_BUILDER_2,
  EXCHANGE_3,   PAGE_URL_3,   API_URL_3,   API_URL_BUILDER_3,

  EXCHANGE_100, PAGE_URL_100, API_URL_100, API_URL_BUILDER_100,
  EXCHANGE_101, PAGE_URL_101, API_URL_101, API_URL_BUILDER_101,
};